### ISSUE TITLE
Music in Jumper is slightly unsynced to the level.

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#102]
**Describe the bug**
Title (i'm pretty sure this is caused by the new music engine, isn't it)

**How to reproduce**
Just play Jumper lol

**Screenshots e/o videos**

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: Phone
 - Emulator [e.g. RetroArch, Mesen]: Nostalgia.NES Pro
 - Core [ONLY if you use RetroArch]:

**Comment by PinguLinux** [comment]
Known bug, Jumper's music got a lil slower,

**Comment by FicusmcHousePlant** [comment]
All music is pending fixes for the new sound driver, and may take some time. It is planned to be fixed for the 1.0 release

**Comment by LNLenost** [comment]
> All music is pending fixes for the new sound driver, and may take some time. It is planned to be fixed for the 1.0 release

Ok thx

**Comment by kandowontu** [comment]
Fixed in https://github.com/famidash/famidash/commit/15ac8dcf7379da806831427bb720bf0d7d7aada8
