### ISSUE TITLE
I wrote a better license

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#104]
Famidash Game License
Revision 2
(c) 2023-2024

1. Any fork of Famidash must credit the original creators in its description and retain this license.

2. You may not claim that any fork of Famidash is your own creation.

3. You may not sell any copy or modification of Famidash.

4. Any copy or modification of Famidash sold to the public or gave away for free without crediting the original creators will be reported and hopefully taken down.

**Comment by PinguLinux** [comment]
Only the original creator ([zephyrside](https://github.com/zephyrside)) can legally change the license.
