### ISSUE TITLE
I might sound crazy, but...

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#108]
Not a lot of people knows Famidash: that's a fact
Everyone uses the Internet: that's a fact

So what if I combine these things and...
I make a WEBSITE for Famidash?

Ofc nothing too complicated, just a WordPress site with the trailer, link to this rep, and a feedback button

What do u guys think?

**Comment by FicusmcHousePlant** [comment]
Might be taking it a little bit too far, but who knows

**Comment by FicusmcHousePlant** [comment]
We do have a twitter, youtube, mastodon, discord, and many online articles mentioning it

**Comment by ZenithNeko** [comment]
don't worry, I'm already working on a famidash info/ad page on my website!!
