### ISSUE TITLE
cycles third coin is a frame-perfect input

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#115]
**Describe the bug**
title

**How to reproduce**
go to where the third coin is and try to collect it (it's a frame-perfect input so good luck doing it without savestates/rewind)

**Screenshots e/o videos**
https://github.com/famidash/famidash/assets/140995410/517c862d-d886-4423-85dd-1aa46f951a9f

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: samsung laptop from 2013 / everdrive n8 pro on real famicom hardware
 - Emulator [e.g. RetroArch, Mesen]: mesen
 - Core [ONLY if you use RetroArch]:

**Comment by kandowontu** [comment]
I can hit it pretty consistently...skill issue

https://github.com/famidash/famidash/assets/95717282/ec740555-c04a-4384-9797-49680288e058
