### ISSUE TITLE
When completing any level, a random sprite appears

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#121]
![Screenshot_20240430_103100_NostalgiaNES Pro.jpg](https://github.com/famidash/famidash/assets/110625168/fd6791e0-1496-4a55-8f7e-a13756ed3ff5)

**Comment by LNLenost** [comment]
Note: this appears in random spots

**Comment by kandowontu** [comment]
This was not so random, it was appearing where the player was when the level end triggered.
This is now fixed!
