### ISSUE TITLE
You can noclip in a block in Stereo Madness

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#128]
(Ignore that this is taken from real GD)
In Platformer Mode, if the ship is placed on the block shown in the image amd you keep A button held, after like 3 seconds you  find yourself in the secret coin route.

![VideoCapture_20240430-135258.jpg](https://github.com/famidash/famidash/assets/110625168/bcd7ef0e-2892-42f1-8319-40a12d233d06)

**Comment by kandowontu** [comment]
Cannot duplicate, doesn't seem to negatively affect the game, will take a note of this but closing it.
