### ISSUE TITLE
Why i'm not marked as tester anymore?

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#131]
I know i'm not the best, and sometimes I'm annoying... but I reported a lot of issues and almost all of them were valid. :(

**Comment by kandowontu** [comment]
We are only including the core members who have been with us since the start, as we are considering a kickstarter and we need to lock down our contributor list.

We do appreciate your issue submissions and your help, but we aren't looking to expand our team any more at this time.

**Comment by LNLenost** [comment]
> We are only including the core members who have been with us since the start, as we are considering a kickstarter and we need to lock down our contributor list.
> 
> We do appreciate your issue submissions and your help, but we aren't looking to expand our team any more at this time.

Also idc about the money.

**Comment by kandowontu** [comment]
> Sorry, but yesterday that was fine and now it isn't?!
> 
> Might as well delete this...
> 
> https://gbatemp.net/threads/homebrew-game-famidash-gets-major-beta-update.655135/

There's a difference between a) getting to know the team, joining the discord, working your way up to becoming part of the team and b) making a ton of issue reports for the sole purpose of getting your name in the credits.

Thank you for the GBAtemp article, though I have a GBAtemp contact already who has already published an article.

Feel free to remove your article if you are unhappy with our collective decisions.

Your issue reports will always be public and viewable by anyone who can see you contributed.

**Comment by LNLenost** [comment]
> > Sorry, but yesterday that was fine and now it isn't?!
> > 
> > Might as well delete this...
> > 
> > https://gbatemp.net/threads/homebrew-game-famidash-gets-major-beta-update.655135/
> 
> There's a difference between a) getting to know the team, joining the discord, working your way up to becoming part of the team and b) making a ton of issue reports for the sole purpose of getting your name in the credits.
> 
> Thank you for the GBAtemp article, though I have a GBAtemp contact already who has already published an article.
> 
> Feel free to remove your article if you are unhappy with our collective decisions.
> 
> Your issue reports will always be public and viewable by anyone who can see you contributed.

I can join the DS then but I use it rarely.

**Comment by kandowontu** [comment]
Regardless of discord or not, we don't have room in the core development team for another member. 

All of us are testing this as we can, and likely would have found the issues you stated over time on our own as well.

We do appreciate you bringing the issues directly to us via bug reports that force us to act, but the team has unanimously agreed that our development team is full and closed.

**Comment by kandowontu** [comment]
> Hey sorry 4 yesterday, I overreacted.

It happens to the best of us, don’t sweat it. :)

**Comment by kandowontu** [comment]
At this point you are now going around youtube videos telling people thank you for playing "our game"...you do not represent our team and are not part of the development team.

At this point we need to make it more clear, so we will be disabling your access to this repo.
