### ISSUE TITLE
UNTIL THIS REPORT IS REMOVED - DO NOT PLAY NIGHTLIES

### ISSUE THREAD

**Issue by kandowontu** [famidash/famidash#132]
We are working on a massive sprite restructuring that may not be done today, but will allow bankswapping sprites as well as additional space. Stay tuned!

Last STABLE nightly before this change: https://cdn.discordapp.com/attachments/1230176045534019586/1235232711665389650/famidash.nes_29.zip?ex=66339f9b&is=66324e1b&hm=c1b061b0abc335b932e639652379dddbf7c001a9c7a659486bf382cc59dd2a3d&

**Comment by LNLenost** [comment]
Playing latest nightly seems one of those horror glitched romhacks

**Comment by zephyrside** [comment]
i originally designed the game to work with symmetrical cube sprites... if you add some that aren't symmetrical then the cube will snap back to an upright position every time it rotates 90 degrees

**Comment by kandowontu** [comment]
> i originally designed the game to work with symmetrical cube sprites... if you add some that aren't symmetrical then the cube will snap back to an upright position every time it rotates 90 degrees

All part of todays fun, figuring out a new rotation routine 😝

**Comment by kandowontu** [comment]
> i originally designed the game to work with symmetrical cube sprites... if you add some that aren't symmetrical then the cube will snap back to an upright position every time it rotates 90 degrees

Yeah after thinking it through this may not work as wanted, and we may be stuck with symmetrical icons.

**Comment by kandowontu** [comment]
Alex may have a solution...if this works, fuckin poggers

**Comment by zephyrside** [comment]
misclick
