### ISSUE TITLE
Comparision between Famidash and Geometry Dash.

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#135]
I did something like RobTop when GD dropped.

If you guys want to, you can upload this somewhere after the new trailer is out.
Link: https://drive.google.com/file/d/1CqTCmC5nbUgpQBSxl843aIyigoJP6yjt/view?usp=drivesdk

**Comment by kandowontu** [comment]
Very cool!!

**Comment by kandowontu** [comment]
Closing but saved video, will credit if used :)
