### ISSUE TITLE
can i have a game genie code for this that forces you on a specific level?

### ISSUE THREAD

**Issue by Rubiidev-18** [famidash/famidash#136]
I need to see glitch levels
also spamming left and right on level selection brings names like `leat go`

**Comment by FicusmcHousePlant** [comment]
I have one for demo 4.0.5, but the glitch levels aren't as interesting as you think

**Comment by kandowontu** [comment]
Level is $0619 ram address

**Comment by FicusmcHousePlant** [comment]
Depends on the build you have. RAM is constantly changing

**Comment by Rubiidev-18** [comment]
> Depends on the build you have. RAM is constantly changing

latest nightly, but gonna try the demo 4.0.5 code

**Comment by FicusmcHousePlant** [comment]
Also yes, you're right with the level names
![Screenshot_20240501_180238_NostalgiaNes Lite](https://github.com/famidash/famidash/assets/153345210/c9b77027-accd-4306-8ce1-5d0ff6ec429e)

**Comment by Rubiidev-18** [comment]
ah yes, my fav gd level, ftere a
                                            base o

**Comment by Rubiidev-18** [comment]
can someone give the the 4.0.5 code

**Comment by FicusmcHousePlant** [comment]
05D2:XX on Famidash 4.05.1

**Comment by FicusmcHousePlant** [comment]
You should just be able to type it in the cheat code box

**Comment by Rubiidev-18** [comment]
what about one for the latest nightly + a list of useful, fun, and other codes? (I wanna fun)

**Comment by Rubiidev-18** [comment]
off topic but I found a corruption code
GTELKTVA+APZLIT

**Comment by kandowontu** [comment]
> off topic but I found a corruption code for nightly GTELKTVA+APZLIT

Added some to https://github.com/famidash/famidash/discussions/137
