### ISSUE TITLE
wave direction is reversed at 3x and 4x speed

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#139]
**Describe the bug**
the wave points in the opposite direction when going at 3x and 4x speed

**How to reproduce**
go to test4

**Screenshots e/o videos**
https://github.com/famidash/famidash/assets/140995410/e0ac4a4d-2254-4bd1-b0f1-432d11455e29

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: samsung laptop running linux mint 21.2
 - Emulator [e.g. RetroArch, Mesen]: mesen
 - Core [ONLY if you use RetroArch]:

**Comment by jaezudev** [comment]
smasnug

**Comment by kandowontu** [comment]
Yeah working on a solution for this one still

**Comment by kandowontu** [comment]
Fixed in https://github.com/famidash/famidash/commit/2cb003189a0eccf872bec7eaa7d8e3dc78d066ef
