### ISSUE TITLE
The floor kills the wave

### ISSUE THREAD

**Issue by Rubiidev-18** [famidash/famidash#148]
**Describe the bug**
The wave gets killed when touching the floor, this is not supposed to happen in the regular gd.

**How to reproduce**
go to test4
touch ground while wave

**Screenshots e/o videos**

https://github.com/famidash/famidash/assets/158863401/cbc41321-f849-4d18-b30a-0b3cd8130382

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: Tablet
 - Emulator [e.g. RetroArch, Mesen]: Nostalgia.NES Pro
 - Core [ONLY if you use RetroArch]:

**Comment by kandowontu** [comment]
This happens if there is no D block in vanilla game. D blocks will likely be added in the near future.

**Comment by zephyrside** [comment]
the floor doesn't kill the wave though, even in the original game

**Comment by PinguLinux** [comment]
Fix'd
