### ISSUE TITLE
you borked my level complete screen lmao

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#163]
**Describe the bug**
https://github.com/famidash/famidash/assets/140995410/58ba80ff-3acd-417c-b9b9-b6ba0c762e6c

**How to reproduce**
beat any level

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: samsung laptop
 - Emulator [e.g. RetroArch, Mesen]: mesen

**Comment by FicusmcHousePlant** [comment]
Well that's new
It never did that before
Strange

**Comment by kandowontu** [comment]
lmao good catch, fixed in https://github.com/famidash/famidash/commit/aaa14bd26e98173f3808074aff2875fae888f48d

thanks!
