### ISSUE TITLE
Is it just me or latest nightly is just a grey screen?

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#184]
I cannot do anything.

**Comment by kandowontu** [comment]
Its just you. Try deleting your save file.

**Comment by kandowontu** [comment]
What emulator are you using

**Comment by LNLenost** [comment]
> What emulator are you using

Nostalgia.NES PRO and i'm also getting this on Mesen's RetroArch core

https://drive.google.com/file/d/1gdQ5JaQ8fu892RaJnP9z5NbCFXbOhdHO/view?usp=drivesdk

**Comment by kandowontu** [comment]
![image](https://github.com/famidash/famidash/assets/95717282/43625d36-3174-4f49-94b9-14530e0e69e0)
Looks fine to me on mesen core on retroarch

**Comment by kandowontu** [comment]
Also fine on delta.
![IMG_4186](https://github.com/famidash/famidash/assets/95717282/63ecb21c-5503-4396-9cd7-3cea2f261190)

**Comment by kandowontu** [comment]
![image](https://github.com/famidash/famidash/assets/95717282/d7bf16ff-d3db-490c-a278-f478eae3a42a)
also fine on nestopia

**Comment by kandowontu** [comment]
Confirmed grey screen on mister. Looking into this.

**Comment by kandowontu** [comment]
Just fixed, PRG banks had to be multiples of 16, so 24 was no good. 32 is working fine on FCEUX/MiSTer/Pocket now.
