### ISSUE TITLE
holding SELECT for 3 secs, makes you win.

### ISSUE THREAD

**Issue by runtwentyh** [famidash/famidash#204]
**Describe the bug**
Holding select while being in a level, noclips your icon for ~3 seconds and shows the "level complete" screen

**How to reproduce**
hold select for ~3 secs or until the win screen pops up

**Screenshots e/o videos**
https://youtu.be/eCOqBSPV5Dc?si=uCXJe-AnuCB-oaN4

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: mobile 
 - Emulator [e.g. RetroArch, Mesen]: NostalgiaNes Lite
 - Core [ONLY if you use RetroArch]: -

**Comment by FicusmcHousePlant** [comment]
This is a debug feature to test the level complete screen, not a bug

**Comment by runtwentyh** [comment]
ah alright
