### ISSUE TITLE
How i can download the game??

### ISSUE THREAD

**Issue by WeferedoneYT** [famidash/famidash#210]
I cant convert the .zip to .nes, how i can convert the game??

**Comment by FicusmcHousePlant** [comment]
Extract the zip file

**Comment by FicusmcHousePlant** [comment]
The nes file is inside of the zip

**Comment by FicusmcHousePlant** [comment]
The latest build can be downloaded as an NES file here:
https://nightly.link/famidash/famidash/workflows/main/main/famidash.nes.zip

**Comment by FicusmcHousePlant** [comment]
Depending on what device you are using, you can also double click the zip and drag the NES file out

**Comment by FicusmcHousePlant** [comment]
If you can't extract the zip on your device, you can use this website:
https://www.ezyzip.com/unzip-files-online.html
