### ISSUE TITLE
Block Fly through glitch

### ISSUE THREAD

**Issue by N-coder82** [famidash/famidash#243]
**Describe the bug**
After spamming buttons, sometimes white lines flash on the screen and then you can't die because you go through any and every block, however if you try to jump you can still stay on top of blocks.

**How to reproduce**
1 Open the game
2 Start a level
3 Spam buttons
**Screenshots e/o videos**

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: iPhone 11 Pro
 - Emulator [e.g. RetroArch, Mesen]: Delta
 - Core [ONLY if you use RetroArch]: N/A

**Comment by kandowontu** [comment]
All you have to do is hit select. That is debug mode.

**Comment by N-coder82** [comment]
Ohhhhhh thank you!
