### ISSUE TITLE
hud complete level and achievements

### ISSUE THREAD

**Issue by TheBoxGame** [famidash/famidash#246]
Hello, will there be a hud of stage completion progress and game achievements available in the game?

**Comment by kandowontu** [comment]
We are working on including this in the game, yes!

**Comment by TheBoxGame** [comment]
@kandowontu thanks I liked the game, will these test stages 1 to 4 be in the game or will they be removed?
oh, and one more thing: will these blue diamonds be added to the game after you die at a given moment in the game?
