### ISSUE TITLE
Diamonds death moments in game 

### ISSUE THREAD

**Issue by TheBoxGame** [famidash/famidash#247]
thanks I liked the game, will these test stages 1 to 4 be in the game or will they be removed?
oh, and one more thing: will these blue diamonds be added to the game after you die at a given moment in the game?
oh, and one more thing, why is there that little mark in the right hand corner of the inscription?
![IMG_20240708_185519](https://github.com/famidash/famidash/assets/109180532/637d9afa-d902-450b-9daf-1f6e7c2e49de)

**Comment by kandowontu** [comment]
Please dont use issues for these questions, use the discussion function :)

Test 1-4 will be removed for final, yes.
Blue diamonds, likely not.
The lock is for future use, likely where the fun settings is moving to.
