### ISSUE TITLE
forgive me kando...

### ISSUE THREAD

**Issue by xboxkh** [famidash/famidash#250]
hello? kando? you there?
what you did was pretty harsh, and yet, i personally do forgive you, but please, do listen to what i must say. I was "_fucking annoying_", and should "_go away_". i get that I was "not welcome here anymore", but getting banned for sending a b3313 screenshot twice? I do get you have 3 kids, but that literally had nothing to do with the situation. just, please... forgive me. 😢

**Comment by SepiaChiptunes** [comment]
GitHub Issues are not a place to beg for forgiveness

**Comment by LNLenost** [comment]
Welcome to my world 💀 apparently, I "absolutely terrify the famidash
github" according to kando on twitter

**Comment by xXFamidashFan69Xx** [comment]
bro pls stop

**Comment by jaezudev** [comment]
womp womp
