### ISSUE TITLE
both players in reverse gravity clip into the floor by 1 extra pixel

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#50]
i'd fix this myself but yall mangled my codebase so much that i have literally no idea how to fix it

**Comment by zephyrside** [comment]
example:
![image](https://github.com/famidash/famidash/assets/140995410/e9c6ed41-82ec-4aa3-8175-d41b817e6ac9)

**Comment by kandowontu** [comment]
Just fixed!
