### ISSUE TITLE
sometimes solid blocks kill the player

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#55]
this part in base after base kills the player and i have no idea why

https://github.com/famidash/famidash/assets/140995410/62f83e71-a6dc-4d34-84bd-a6f78e59c770

**Comment by kandowontu** [comment]
noooooo my collision system broke again ;_;

**Comment by kandowontu** [comment]
its being triggered in bg_coll_death

**Comment by kandowontu** [comment]
This is now fixed, pushing update
