### ISSUE TITLE
level editor.

### ISSUE THREAD

**Issue by rubiidev18alt** [famidash/famidash#56]
## all in the title.

for the basic proto of the editor:

    push b in lvl select to access it.   dpad to move cursor.   select
    to change block   a to place   b to remove   start to access the
    editor pause menu   start again in pause menu to play current level 
    select in pause menu to move cursor to a button   b to go back to
    editor   a in pause menu to choose your starting gamemode, mini or
    not, song, and some other stuff   for triggers (only bg and g color
    for now):   a on a placed trigger to edit   left and right on dpad
    to change the color to a predefined one from the main levels

that's all I'm gonna give you, work on it with these controls in mind.  

###### (or go the excitebike a to z chunks way idc)

edit: you can use this image from the old repo + from an old commit of the old repo for the color triggers and colors themselves
![sprites](https://github.com/famidash/famidash/assets/164731988/8c1e10f9-e9c2-4944-ba57-e9542a6d84d2)

**Comment by zephyrside** [comment]
not planned but might be doable with a lock-on cartridge
more on that in the future
