### ISSUE TITLE
anything else we should finish before demo 5 or release 1.0?

### ISSUE THREAD

**Issue by zephyrside** [famidash/famidash#59]
since i can't get on the discord just yet i figured this was the best way to communicate

**Comment by zephyrside** [comment]
just added sfx stuff to the menus

**Comment by ADM228** [comment]
ima be honest, for some time a chunk of the team (maybe the majority even) has been thinking of changing the license to something with more legal merit

quote from jrowe:
"okay next up on the dream list: relicensing to apache 2 or MIT
both of them require the same stuff chell's license does
but with actual boring legaleese instead of thing that prevents any real distribution rights in the future :p"

However we have no legal permission to do this (you created the thing after all) so only you can do this lmao

**Comment by FicusmcHousePlant** [comment]
I have a few menuscreens left to create and I'm also planning on adding custom icons for the icon edit screen (the first nine icons unlocked by beating levels up to cycles). The artwork has been created, but I just have to figure out rotation. These icons will replace the default icon through bankswitching which we have planned for sprites
![1713821503973](https://github.com/famidash/famidash/assets/153345210/396406f7-c82a-4535-b27a-47a9741f55ea)

**Comment by FicusmcHousePlant** [comment]
I'm also not sure what to do with the level edit screen (lock-on custom levels maybe?)

**Comment by FicusmcHousePlant** [comment]
For levels, we have 1.0 planned to have levels up to Theory of Everything. The plan was up to Cycles, but ale did XStep, which needed new tilesets

**Comment by kandowontu** [comment]
Mini collision is now fixed, we can do clutterfunk and TOE :D

**Comment by LNLenost** [comment]
Gg!!

Il Ven 26 Apr 2024, 20:15 kandowontu ***@***.***> ha scritto:

**Comment by LNLenost** [comment]
Also i found a bug in the nightly version. If you open Jumper, some seconds
after the part where the cube is at the top of the screen, you die by
landing on the slabs.

Il Ven 26 Apr 2024, 20:15 kandowontu ***@***.***> ha scritto:

**Comment by zephyrside** [comment]
> ima be honest, for some time a chunk of the team (maybe the majority even) has been thinking of changing the license to something with more legal merit
> 
> quote from jrowe: "okay next up on the dream list: relicensing to apache 2 or MIT both of them require the same stuff chell's license does but with actual boring legaleese instead of thing that prevents any real distribution rights in the future :p"
> 
> However we have no legal permission to do this (you created the thing after all) so only you can do this lmao

will consider changing the license before the 1.0 release

**Comment by zephyrside** [comment]
oh my god
the fact that yall made platformer mode this early is hilarious
10/10 idea

**Comment by Rubiidev-18** [comment]
> Mini collision is now fixed, we can do clutterfunk and TOE :D

see #69, might be device parity as I'm on a galaxy tab s9 and lz is on a s24 fe

**Comment by kandowontu** [comment]
TOE work starts tomorrow!

**Comment by zephyrside** [comment]
sweet
how are we gonna do the new tiles? because of how gd levels are, i initially left as much of it open as possible for unique tiles so that any metatile could be used at any time for custom levels. seems like yall undid that with the parallax

**Comment by FicusmcHousePlant** [comment]
Parallax uses no metatiles. As for new blocks, we would need a CHR swap to fit them all in

**Comment by FicusmcHousePlant** [comment]
Ex. ToE's brick tiles will be swapped with the 1.0 checker blocks

**Comment by kandowontu** [comment]
This will only work right now if the Chr and metatiles are in the exact same spot as what is being replaced, and will just require a Chr swap when the level is chosen. I hope.

**Comment by kandowontu** [comment]
The new branch is to see if it’s possible to have a full alternate metatile set

**Comment by FicusmcHousePlant** [comment]
And that's the plan. The Bricks in the CHR replace the 1.0 checker blocks, and will line up in the metatiles

**Comment by zephyrside** [comment]
wait, hear me out

**t i l e s e t   t r i g g e r s**

when loaded into the sprite renderer, it changes which tileset is used by the game, similar to how the color triggers change the background color

**Comment by FicusmcHousePlant** [comment]
Cool idea, but we might put what CHR the level uses in the header

**Comment by zephyrside** [comment]
i guess that could work

**Comment by kandowontu** [comment]
> wait, hear me out
> 
> **t i l e s e t t r i g g e r s**
> 
> when loaded into the sprite renderer, it changes which tileset is used by the game, similar to how the color triggers change the background color

This would be the way, we just need to figure out how to have a separate set of tile definitions and attributes that load for it…

**Comment by zephyrside** [comment]
oh hey btw @ADM228 how do i export the music from fs to work with banks

**Comment by ADM228** [comment]
@zephyrside only export a few songs at a time and ensure the total assembly size less than 8192 bytes
Some of the guesswork has been removed since FS 4.2.0 introduced folders 
Also there's the good old DPCM aligner if you know what i mean

**Comment by Rubiidev-18** [comment]
#94 (maybe shorten the pad hitbox a tiny bit)

**Comment by kandowontu** [comment]
> #94 (maybe shorten the pad hitbox a tiny bit)

The pad has a hitbox wide size of 16 pixels and a height of 2 pixels.

**Comment by Rubiidev-18** [comment]
> The pad has a hitbox wide size of 16 pixels and a height of 2 pixels.

maybe just decrease it by 2 pixels (as you see, I'm helping, you should add me as a issue helper)

**Comment by kandowontu** [comment]
> > The pad has a hitbox wide size of 16 pixels and a height of 2 pixels.
> 
> maybe just decrease it by 2 pixels (as you see, I'm helping, you should add me as a issue helper)

I dont see a problem with #94 - The cube missed the spike hitbox (a small rectangle in the middle of the spike) - its working BETTER than expected thanks to the new collision routines.

**Comment by kandowontu** [comment]
@zephyrside most of us have agreed that we should start looking into running a kickstarter. Just wanted to see your thoughts on this, and obviously you will be recieving a cut just like everyone else.

**Comment by zephyrside** [comment]
> @zephyrside most of us have agreed that we should start looking into running a kickstarter. Just wanted to see your thoughts on this, and obviously you will be recieving a cut just like everyone else.

sounds like a good idea, although i don't exactly know the legality of it

**Comment by kandowontu** [comment]
I’ve reached out to rubrub twice already but no response. Given his history of support fan games as well as telling people to just pirate his game, I’d say he likely won’t mind. Will personally put aside a portion of my own in case he decides he would like to receive 85 as I offered to him.

Obviously we are a little ways away from doing anything, still in the brainstorming phase. We all agreed we will also keep the project open source no matter what happens.

Hopefully we can make something happen!

**Comment by zephyrside** [comment]
alright then yeah, lets do a kickstarter
let me set it up though, i'm cooking an 80's style trailer for the game that would fit perfectly with it

**Comment by zephyrside** [comment]
> Nice!
> Question: what if we made some vids about Famidash on YT? Smth like robtop did (posting vids about completing levels and showcasing the icon kit)

ye i'll probably do that on my channel

**Comment by LNLenost** [comment]
Also, I personally think people would have more "security" to donate on a Patreon with the game's name instead of kando's one: with Famidash it feels more "legit": same for Twitter.

**Comment by LNLenost** [comment]
> > Nice!
> > Question: what if we made some vids about Famidash on YT? Smth like robtop did (posting vids about completing levels and showcasing the icon kit)
> 
> ye i'll probably do that on my channel

Ok

**Comment by zephyrside** [comment]
> > > Nice!
> > > Question: what if we made some vids about Famidash on YT? Smth like robtop did (posting vids about completing levels and showcasing the icon kit)
> > 
> > 
> > ye i'll probably do that on my channel
> 
> Ok, link?

i don't have very much on it that's publicly viewable at the moment but yeah here [https://www.youtube.com/@UserSniper](url)

**Comment by LNLenost** [comment]
Thx, subbed

**Comment by kandowontu** [comment]
> alright then yeah, lets do a kickstarter
> let me set it up though, i'm cooking an 80's style trailer for the game that would fit perfectly with it

Wooo!!!

**Comment by ADM228** [comment]
> alright then yeah, lets do a kickstarter let me set it up though, i'm cooking an 80's style trailer for the game that would fit perfectly with it

NOICEEEE

I'll take on at least some of the manufacturing

**Comment by FicusmcHousePlant** [comment]
I've already started work on the game pak label

**Comment by zephyrside** [comment]
![cart design](https://github.com/famidash/famidash/assets/140995410/a5fa00cf-ca9a-40a1-900a-fb355cfe93e8)
hear me out

**Comment by FicusmcHousePlant** [comment]
Hoping the lock on levels are doable

**Comment by FicusmcHousePlant** [comment]
Would be fun

**Comment by zephyrside** [comment]
ye

**Comment by FicusmcHousePlant** [comment]
The lock on levels menu is currently being used to test out the fun settings menu Kando made. This fun settings menu will be moved to the level select and will be accessed via beating all levels or collecting all secret coins. Will add the lock-on levels screen back after we move it over

**Comment by zephyrside** [comment]
alr

**Comment by FicusmcHousePlant** [comment]
For when we do make the carts, what color should the cart be? Was thinking dark green would look cool with the blue label

**Comment by FicusmcHousePlant** [comment]
Also not sure if nes lock on carts are a thing

**Comment by zephyrside** [comment]
nah, we can make our own cart (if we do the kickstarter)

**Comment by Rubiidev-18** [comment]
> nah, we can make our own cart (if we do the kickstarter)

well I could (did I cook?)
![Uploading Untitled39_20240502155208.png…]()

**Comment by Rubiidev-18** [comment]
![Untitled39_20240502155208](https://github.com/famidash/famidash/assets/158863401/543c66ab-c506-4026-8b11-05631c0bcd80)

**Comment by Rubiidev-18** [comment]
pin this issue or transfer everything into a discussion

**Comment by FicusmcHousePlant** [comment]
Well, I meant the custom level lock-on

**Comment by Rubiidev-18** [comment]
rough concept of the custom level lock on cart (might use same tech as game genie)
![Untitled40_20240502160305](https://github.com/famidash/famidash/assets/158863401/f53b3afc-38dd-4b5a-b64b-1def502502fa)

**Comment by zephyrside** [comment]
> Well, I meant the custom level lock-on cart. I'm not sure if such a thing exists for the NES.

should be easy enough if we just have a ROM chip on the level carts that gets mapped to the MMC3 address space

**Comment by Rubiidev-18** [comment]
> > Well, I meant the custom level lock-on cart. I'm not sure if such a thing exists for the NES.
> 
> should be easy enough if we just have a ROM chip on the level carts that gets mapped to the MMC3 address space

then we might need to add a lvl editor to the lock on thing (+ disable the editor icon and change it into a fun settings icon if not locked on and enable when locked on), right?

**Comment by zephyrside** [comment]
> > > Well, I meant the custom level lock-on cart. I'm not sure if such a thing exists for the NES.
> > 
> > 
> > should be easy enough if we just have a ROM chip on the level carts that gets mapped to the MMC3 address space
> 
> then we might need to add a lvl editor to the lock on thing (+ disable the editor icon and change it into a fun settings icon if not locked on and enable when locked on), right?

i mean, it is the modern day
people could make their own levels with a computer, and then flash it to a level pak
granted, they'd have to purchase one of those famicom dev cart flashers, assuming we use the same cartridge port for the level paks

**Comment by Rubiidev-18** [comment]
> > > > Well, I meant the custom level lock-on cart. I'm not sure if such a thing exists for the NES.
> > > 
> > > 
> > > should be easy enough if we just have a ROM chip on the level carts that gets mapped to the MMC3 address space
> > 
> > 
> > then we might need to add a lvl editor to the lock on thing (+ disable the editor icon and change it into a fun settings icon if not locked on and enable when locked on), right?
> 
> i mean, it is the modern day people could make their own levels with a computer, and then flash it to a level pak granted, they'd have to purchase one of those famicom dev cart flashers, assuming we use the same cartridge port for the level paks

then we def need a pc level editor program that looks a lot like the gd one with al, the features so far, devs get on to that

**Comment by FicusmcHousePlant** [comment]
We use Tiled to build all the Famidash levels.

**Comment by Rubiidev-18** [comment]
> We use Tiled to build all the Famidash levels.

wait, is there a mobile version, also, link????????? /hj

**Comment by FicusmcHousePlant** [comment]
If a level isn't locked onto the cart, the custom level screen would likely show a prompt to plug in a level lock-on

**Comment by FicusmcHousePlant** [comment]
This whole level lock-on thing is for the distant future. Our main focus for now is customizable icons and Theory of Everything.

**Comment by Rubiidev-18** [comment]
> If a level isn't locked onto the cart, the custom level screen would likely show a prompt to plug in a level lock-on

literally the most logical thing. you can make a concept of that + the editor and other custom lvl stuff yourself

**Comment by Rubiidev-18** [comment]
> This whole level lock-on thing is for the distant future. Our main focus for now is customizable icons and Theory of Everything.

ye, to do this, we literally need another graphics.png

**Comment by FicusmcHousePlant** [comment]
The icons are loaded into the CHR using bankswitching
![Screenshot 2024-05-01 195951](https://github.com/famidash/famidash/assets/153345210/c6f678f0-3520-4e82-986a-a3ca2d390591)

**Comment by Rubiidev-18** [comment]
wait so does that mean I could make my own icon in a famidash fork (also full robtop mini ufo icon pls it's so cute)

**Comment by FicusmcHousePlant** [comment]
Yeah, when 1.0 or 0.5 releases, feel free to do a romhack! There will be several icon banks to customize (As the artist, the cube's rotations are NOT easy to draw). The icons are not yet functional, as we need to get them working with all possible cube landing angles and rotations.

**Comment by FicusmcHousePlant** [comment]
But if you'd like to just mess around before then, Here's a template icon bank for customization (had to be put into a ZIP file).
[bankicon00.zip](https://github.com/famidash/famidash/files/15195418/bankicon00.zip)

**Comment by FicusmcHousePlant** [comment]
NOTE: We will only be adding 1.0 icons and other icons earned from beating levels like Time machine and Cycles to Famidash. All the artwork has been created for them.

**Comment by zephyrside** [comment]
> > > > > Well, I meant the custom level lock-on cart. I'm not sure if such a thing exists for the NES.
> > > > 
> > > > 
> > > > should be easy enough if we just have a ROM chip on the level carts that gets mapped to the MMC3 address space
> > > 
> > > 
> > > then we might need to add a lvl editor to the lock on thing (+ disable the editor icon and change it into a fun settings icon if not locked on and enable when locked on), right?
> > 
> > 
> > i mean, it is the modern day people could make their own levels with a computer, and then flash it to a level pak granted, they'd have to purchase one of those famicom dev cart flashers, assuming we use the same cartridge port for the level paks
> 
> then we def need a pc level editor program that looks a lot like the gd one with al, the features so far, devs get on to that

i actually had this planned, but then december 31 happened and the other devs mangled my compression
now i have no idea how to build the level data

**Comment by ADM228** [comment]
> ![cart design](https://private-user-images.githubusercontent.com/140995410/327603259-a5fa00cf-ca9a-40a1-900a-fb355cfe93e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDA0NTEsIm5iZiI6MTcxNDc0MDE1MSwicGF0aCI6Ii8xNDA5OTU0MTAvMzI3NjAzMjU5LWE1ZmEwMGNmLWNhOWEtNDBhMS05MDBhLWZiMzU1Y2ZlOTNlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMjQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDU2Y2M2YmNjOGEyMmJjMDlmZGEyNmIyMGRlZjQ0OWM3MGJhOTgzY2E5Mjk4MDhjYThiMDY1YzgzZjVjZTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QzC6poULda6fNrBXdvXTn_sLX8gopFivco5-SHxDkXo) hear me out
@zephyrside 

the most i can do is  alladin deck enhancer style beat

![image](https://github.com/famidash/famidash/assets/91823517/0aa98ee8-de4b-4b2b-a990-b1e6775fca26)

speciifcally the master cart has the MMC3 clone, AVR CIC (the unlocking chip), and the RAM needed for a 4-screen nametable; while the smaller cart contains the *entire* PRG and CHR ROM chips (as well as SRAM because you need to save per cart)

this would make it less famidash-specific, yes
BUT it would be a possiblity to be an accessible MMC3-based developing/testing platform
+ the game would work on FCs and NTSC NESs interchangeably lmao

**Comment by zephyrside** [comment]
true...
i had an idea for the code problem though, more on that later when i'm finished cooking

**Comment by FicusmcHousePlant** [comment]
The level storing and loading was greatly optimized by Jrowe, saving around 65% of level banks

**Comment by FicusmcHousePlant** [comment]
Was desperately needed because of clutterfunk

**Comment by FicusmcHousePlant** [comment]
Hopefully we can help you out with all the big changes when you get discord back eventually

**Comment by zephyrside** [comment]
ye i've got some other things to work out first, but i'll be able to return soon i swear

**Comment by FicusmcHousePlant** [comment]
No worries, take your time

**Comment by FicusmcHousePlant** [comment]
Oh I should also point out that we made a new server due to the old one being at risk since we didn't have any perms. The new one has almost 300 members!

**Comment by zephyrside** [comment]
poggers

**Comment by zephyrside** [comment]
lmao
![image](https://github.com/famidash/famidash/assets/140995410/6610f428-0ad3-47dc-b2a6-8b8388cbc631)

**Comment by FicusmcHousePlant** [comment]
To stop bug reports

**Comment by zephyrside** [comment]
understandable

**Comment by kandowontu** [comment]
Hey @zephyrside we have another opportunity to make some money, as we have an offer to make a reskinned version of famidash to be used *inside* of a future steam game using unreal engine, just as a fun mini-game/easter egg.

Maybe some custom screens and levels based on their music. 

Of course you're going to be included in the payout!

I wanted to make sure you're cool with this, and also hoping you could change the license to something standard so that there wouldn't be any reason for their legal team to have concerns.

Lets get paid!

**Comment by zephyrside** [comment]
> Hey @zephyrside we have another opportunity to make some money, as we have an offer to make a reskinned version of famidash to be used _inside_ of a future steam game using unreal engine, just as a fun mini-game/easter egg.
> 
> Maybe some custom screens and levels based on their music.
> 
> Of course you're going to be included in the payout!
> 
> I wanted to make sure you're cool with this, and also hoping you could change the license to something standard so that there wouldn't be any reason for their legal team to have concerns.
> 
> Lets get paid!

oooh i like the idea
elaborate more on this game that you speak of

**Comment by Rubiidev-18** [comment]
> > Hey @zephyrside we have another opportunity to make some money, as we have an offer to make a reskinned version of famidash to be used _inside_ of a future steam game using unreal engine, just as a fun mini-game/easter egg.
> > Maybe some custom screens and levels based on their music.
> > Of course you're going to be included in the payout!
> > I wanted to make sure you're cool with this, and also hoping you could change the license to something standard so that there wouldn't be any reason for their legal team to have concerns.
> > Lets get paid!
> 
> oooh i like the idea elaborate more on this game that you speak of

I got some ideas:
reskin everything to fit the game
make it maybe 8 star.
make it challenging.
maybe make each level unlockable thru quests
not an idea, but:
show us the rom for the latest build of this reskin too

**Comment by FicusmcHousePlant** [comment]
The Special Edition is mostly going to be an early peek as to what's coming in 1.0 and will have different levels and music

**Comment by FicusmcHousePlant** [comment]
Kinda like Subzero and Meltdown

**Comment by Rubiidev-18** [comment]
@FicusmcHousePlant show us an preview

**Comment by FicusmcHousePlant** [comment]
We haven't started work on it yet

**Comment by FicusmcHousePlant** [comment]
But you can get the latest build here on git

**Comment by Rubiidev-18** [comment]
> But you can always get the latest in-development build of Famidash here on Github

yea ik

will it be worked on in a famidash fork

**Comment by FicusmcHousePlant** [comment]
Most likely yeah

**Comment by kandowontu** [comment]
> > Hey @zephyrside we have another opportunity to make some money, as we have an offer to make a reskinned version of famidash to be used _inside_ of a future steam game using unreal engine, just as a fun mini-game/easter egg.
> > Maybe some custom screens and levels based on their music.
> > Of course you're going to be included in the payout!
> > I wanted to make sure you're cool with this, and also hoping you could change the license to something standard so that there wouldn't be any reason for their legal team to have concerns.
> > Lets get paid!
> 
> oooh i like the idea elaborate more on this game that you speak of

Its called Vectorball ( https://store.steampowered.com/app/2512660/VectorBall/ )
The guy gives away pizza gift cards almost every day on the discord, and the developers are cool af.
They've already commissioned me a few hundred (minimum) to help develop a standalone homebrew for it as well lmao.

I'll try to get steam codes for the team!

**Comment by LNLenost** [comment]
> Its called Vectorball ( https://store.steampowered.com/app/2512660/VectorBall/ )
> The guy gives away pizza gift cards almost every day on the discord, and the developers are cool af.
> They've already commissioned me a few hundred (minimum) to help develop a standalone homebrew for it as well lmao.
> 
> I'll try to get steam beta codes for the team!

Ngl the game seems FIRE

Also today I will prob join the Famidash discord

**Comment by zephyrside** [comment]
> Its called Vectorball ( https://store.steampowered.com/app/2512660/VectorBall/ ) The guy gives away pizza gift cards almost every day on the discord, and the developers are cool af. They've already commissioned me a few hundred (minimum) to help develop a standalone homebrew for it as well lmao.
> 
> I'll try to get steam beta codes for the team!

this game looks sick as hell, i'm all for it

**Comment by kandowontu** [comment]
Lfg!! Just submitted a proposal!

**Comment by kandowontu** [comment]
@zephyrside send me an email, we’ve been greenlit. Want to go over your cut. Kandowontu@me.com

**Comment by zephyrside** [comment]
> @zephyrside send me an email, we’ve been greenlit. Want to go over your cut. [Kandowontu@me.com](mailto:Kandowontu@me.com)

will do soon
first i gotta make sure that i don't have a repeat of december 31 2023 by getting in direct contact with you

**Comment by kandowontu** [comment]
@zephyrside are you still down for making music?

**Comment by zephyrside** [comment]
> @zephyrside are you still down for making music?

i'm a bit rusty due to the 4 month absence but i can give it a shot

**Comment by kandowontu** [comment]
Wanna give base after base a shot? :D

**Comment by zephyrside** [comment]
sure

**Comment by zephyrside** [comment]
i love 2 player mode
https://github.com/famidash/famidash/assets/140995410/e3dc96cc-34d5-4276-96f3-2809ae9c8464

even without the visible pads the game struggles lmao

**Comment by kandowontu** [comment]
It’s so bad 😭😭😭

**Comment by zephyrside** [comment]
oh btw, we should probably shrink the size of the parallax chr if we ever want more than one background

**Comment by FicusmcHousePlant** [comment]
I'm not sure if that's possible without making the background repetitive

**Comment by FicusmcHousePlant** [comment]
We wouldn't need a new background until Electrodynamix anyways, which is in the distant future after 1.0

**Comment by FicusmcHousePlant** [comment]
Even then I don't think it'd be worth it

**Comment by zephyrside** [comment]
we can probably cut the size down a bit by having only two upward offsets instead of three

**Comment by FicusmcHousePlant** [comment]
Created a todo list for 1.0. Getting very close to finalizing all the levels.

**Comment by ADM228** [comment]
Yo @zephyrside happy birthday

**Comment by LNLenost** [comment]
Happy birthday @zephryside 🥳🥳

**Comment by FicusmcHousePlant** [comment]
Oh yeah happy birthday! 🎂🎉

**Comment by kandowontu** [comment]
Closing since we dont have to communicate through here anymore
