### ISSUE TITLE
I can jump on the spikes in Dry Out without dying

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#63]
So, I'm using the latest version of FamiDash nightly. In a specific part of the level, I can jump on the spikes without dying. This bug works both on my phone (using Nostalgia.NES Pro), PC (RetroArch) and Nintendo Switch (RetroArch again)

Proof attached.

https://github.com/famidash/famidash/assets/110625168/91b82d2c-3b46-414c-9228-7b704d1ce4f4

**Comment by jaezudev** [comment]
What core did you use in RetroArch?
Additionally, please try with Mesen as well if you're able to.

**Comment by LNLenost** [comment]
Mame 2000.

**Comment by kandowontu** [comment]
I just confirmed this happens on mesen as well

**Comment by LNLenost** [comment]
I'll check this again tomorrow. Good night! :D

**Comment by kandowontu** [comment]
This is now fixed

**Comment by LNLenost** [comment]
> This is now fixed

Thanks! Is the patch already out on the nightly?
