### ISSUE TITLE
2 player mode has laggggg in some levels

### ISSUE THREAD

**Issue by kandowontu** [famidash/famidash#68]
blaring example: cycles

**Comment by zephyrside** [comment]
i mean yeah, you're trying to draw 2 players, up to 16 objects, and have them all collide in the same frame
what were you expecting lmao

tbh i don't mind having a small amount of slowdown in the game, since i already lag-proofed the sound engine a while ago

**Comment by ADM228** [comment]
Currently doing this, saved like 6.5K (bytes, not cycles, but that should correlate)

**Comment by ADM228** [comment]
sending my fork to @kandowontu for testing

**Comment by kandowontu** [comment]
Almost there...lag is gone but player 1 does not collide with sprites.

Close...!

**Comment by ADM228** [comment]
> player 1 does not collide with sprites.
yea that sems about right
![image](https://github.com/famidash/famidash/assets/91823517/72c4d063-b1ed-4e2e-9615-bf18f7c7ab18)

**Comment by ADM228** [comment]
also yes, the entire thing i did is literally store `player_x`, `_y`, `_vel_x`, `_vel_y` and _gravity[currplayer]` into vars in the zeropage
cc65 is *absolutely horrible* at dynamically indexing arrays of shorts btw

**Comment by ADM228** [comment]
status update:
![image](https://github.com/famidash/famidash/assets/91823517/2ed2bb43-c0ed-4b5b-8ffd-9eb2d34d6afa)

**Comment by kandowontu** [comment]
Holy shit

**Comment by ADM228** [comment]
pretty much solved by #116
