### ISSUE TITLE
[bug] cant get to 1st ship part in clutterfunk

### ISSUE THREAD

**Issue by Rubiidev-18** [famidash/famidash#69]
I can't get past the cube in clutterfunk, maybe due to the saw hitbox being bigger than gd, see video for proof.

https://github.com/famidash/famidash/assets/158863401/a9a2c752-1277-4a53-ab4e-9477002fa2b7

maybe I have to time the pad, idk, maybe make saw hitboxes a bit smaller

**Comment by LNLenost** [comment]
Ignoring how I miserably died, I'm using Nostalgia.NES Pro too and Famidash nightly version, but I haven't got this issue.

https://github.com/famidash/famidash/assets/110625168/9885d5e6-a882-41d1-b787-cb9ea501d584

**Comment by Rubiidev-18** [comment]
@LNLenost have you tried jumping at the same spot I jumped on the pad on?
