### ISSUE TITLE
Second coin route in Base After Base doesn't give the coins and kills you.

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#70]
Using Nostalgia.NES Pro with Famidash nightly. Sorry if the recording is short but I wasn't recording when this happened.

https://github.com/famidash/famidash/assets/110625168/56251cb5-a880-4397-bae1-4f0a163d6535

**Comment by Rubiidev-18** [comment]
physics might need to be temp be 0.5x speed for this part maybe

**Comment by LNLenost** [comment]
> physics might need to be temp be 0.5x speed for this part maybe
> don't know `about the not getting coin` part tho

When I enter the portal, I don't touch the coin so I can't get it.
