### ISSUE TITLE
When you complete Base after Base, the first letter turns orange and blue

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#78]
Yeah it should be white...
Using Nostalgia.NES Pro and Famidash nightly.

![Screenshot_20240427_183704_NostalgiaNES Pro.jpg](https://github.com/famidash/famidash/assets/110625168/e71aa287-d85d-4f6a-9a30-079ee57b7fd7)

**Comment by kandowontu** [comment]
This is now fixed, thank you!

**Comment by LNLenost** [comment]
Np :D
