### ISSUE TITLE
Blocks don't kill you in platformer mode when crahing onto them

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#81]
I refuse to tell which device I'm using and which version, you know that by now for sure

https://github.com/famidash/famidash/assets/110625168/e2c8a3ea-91d1-4ee3-ac25-0d98a3e596ae

**Comment by kandowontu** [comment]
Thats intentional and an added feature

**Comment by LNLenost** [comment]
> Thats intentional and an added feature

Oops sorry

**Comment by mak448a** [comment]
Hi, I recently found this amazing project and ran into this feature quite a few times. How do you deactivate it?
