### ISSUE TITLE
Missing spike in Base After Base

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#93]
That triggers me so much

 ![Screenshot_20240428_092030_NostalgiaNES Pro.jpg](https://github.com/famidash/famidash/assets/110625168/982a55a4-dc34-480a-a94d-41960ee46abf)

**Comment by PinguLinux** [comment]
That spike is also missing in geometry dash so it will probably stay.

**Comment by LNLenost** [comment]
> That spike is also missing in geometry dash so it will probably stay.

Yeah I forgor about that

**Comment by FicusmcHousePlant** [comment]
Yeah I added it in bc RobTop missed the spike too, so it's for the funny
