### ISSUE TITLE
Jump pad in Back on Track works even if jumping on spikes

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#94]
Just keep "A" button held from the beginning of the level to replicate

https://github.com/famidash/famidash/assets/110625168/f27b1f9b-e223-44f6-aa7f-ce2600a90540

**Comment by kandowontu** [comment]
https://github.com/famidash/famidash/assets/95717282/53702827-0de1-452e-a2e1-a29fc9d14150

Looks ok to me, spike hitbox is supposed to have some dead space around the middle.
