### ISSUE TITLE
Enabling NoClip mode creates a visual bug on top of the screen

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#96]
This happens in any level

https://github.com/famidash/famidash/assets/110625168/fbf56d85-ceaf-49cd-a811-bfdc9bff7e39

**Comment by PinguLinux** [comment]
Thats not a visual bug, its a cpu usage meter.

**Comment by FicusmcHousePlant** [comment]
Well, the CPU usage meter does leave some strange colors above, but it's a quick and dirty debug feature and most likely won't be fixed.
